# Generated by Django 3.1.4 on 2022-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220130_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='admission_number',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='full_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='mother_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='upload_Resume',
            field=models.FileField(default='', max_length=254, upload_to=None),
        ),
    ]
