# Generated by Django 3.1.4 on 2022-02-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220130_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='StudentDetail',
        ),
    ]
