# Generated by Django 3.1.4 on 2022-02-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220209_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('upload_file', models.FileField(default='', max_length=254, upload_to=None)),
            ],
        ),
    ]
