# Generated by Django 3.1.4 on 2022-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_placementdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobform',
            name='status',
        ),
        migrations.AddField(
            model_name='jobform',
            name='link_to_apply',
            field=models.URLField(default=''),
        ),
    ]
