# Generated by Django 3.1.4 on 2022-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20220212_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('profile', models.CharField(default='', max_length=30)),
                ('skills', models.CharField(default='', max_length=50)),
                ('stipend', models.IntegerField(default=0)),
                ('duration', models.CharField(default='', max_length=15)),
                ('last_date', models.CharField(default='', max_length=15)),
                ('link_to_apply', models.URLField(default='')),
            ],
        ),
    ]
