# Generated by Django 3.1.4 on 2022-02-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0006_internshipform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='', max_length=254, upload_to=None)),
                ('is_selected', models.BooleanField(default=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobform')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
